-- CreateTable
CREATE TABLE `ADMIN` (
    `idADMIN` INTEGER NOT NULL,
    `nombre` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `activo` BOOLEAN NOT NULL DEFAULT true,
    `password` VARCHAR(191) NOT NULL,
    `foto` VARCHAR(191) NULL,

    UNIQUE INDEX `ADMIN_email_key`(`email`),
    PRIMARY KEY (`idADMIN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CENTRO` (
    `idCENTRO` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idCENTRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AMBIENTE` (
    `idAMBIENTE` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `caracteristicas` VARCHAR(500) NOT NULL,
    `centroId` INTEGER NOT NULL,

    PRIMARY KEY (`idAMBIENTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA` (
    `idPROGRAMA` INTEGER NOT NULL AUTO_INCREMENT,
    `nivel` VARCHAR(50) NOT NULL,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` TEXT NOT NULL,
    `activo` BOOLEAN NOT NULL DEFAULT true,
    `centroId` INTEGER NOT NULL,
    `programaId` INTEGER NULL,
    `reporteId` INTEGER NULL,

    PRIMARY KEY (`idPROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RECOMENDACION` (
    `idRECOMENDACION` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,
    `ranking` INTEGER NOT NULL DEFAULT 0,
    `programaElegidoId` INTEGER NULL,
    `reporteId` INTEGER NOT NULL,

    PRIMARY KEY (`idRECOMENDACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ASPIRANTE` (
    `idASPIRANTE` INTEGER NOT NULL,
    `nombre_completo` VARCHAR(50) NOT NULL,
    `fechaNacimiento` DATE NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `telefono` VARCHAR(10) NOT NULL,
    `barrio` VARCHAR(100) NOT NULL,
    `direccion` VARCHAR(100) NOT NULL,
    `ocupacion` VARCHAR(191) NOT NULL,
    `institucion` VARCHAR(191) NULL,
    `activo` BOOLEAN NOT NULL DEFAULT true,
    `password` VARCHAR(191) NOT NULL,
    `foto` VARCHAR(191) NULL,

    PRIMARY KEY (`idASPIRANTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CODIGO_VERIFICACION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(100) NOT NULL,
    `codigo` VARCHAR(6) NOT NULL,
    `datos` JSON NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `CODIGO_VERIFICACION_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TEST` (
    `idTEST` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idTEST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REPORTE` (
    `idREPORTE` INTEGER NOT NULL AUTO_INCREMENT,
    `Fecha` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `puntajeR` INTEGER NOT NULL DEFAULT 0,
    `puntajeI` INTEGER NOT NULL DEFAULT 0,
    `puntajeA` INTEGER NOT NULL DEFAULT 0,
    `puntajeS` INTEGER NOT NULL DEFAULT 0,
    `puntajeE` INTEGER NOT NULL DEFAULT 0,
    `puntajeC` INTEGER NOT NULL DEFAULT 0,
    `testId` INTEGER NOT NULL,
    `aspiranteId` INTEGER NOT NULL,

    PRIMARY KEY (`idREPORTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREGUNTAS` (
    `idPREGUNTAS` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `perfilesRIASEC` VARCHAR(50) NULL,
    `generadaIA` BOOLEAN NOT NULL DEFAULT true,
    `testId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREGUNTAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESPUESTAS_ASPIRANTE` (
    `idRESPUESTASASP` INTEGER NOT NULL AUTO_INCREMENT,
    `valor` INTEGER NULL,
    `texto` TEXT NULL,
    `aspiranteId` INTEGER NOT NULL,
    `preguntaId` INTEGER NOT NULL,
    `reporteId` INTEGER NOT NULL,

    PRIMARY KEY (`idRESPUESTASASP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `APRENDIZ` (
    `idAPRENDIZ` INTEGER NOT NULL,
    `tipoDocumento` VARCHAR(50) NOT NULL,
    `nombre` VARCHAR(100) NOT NULL,
    `apellidos` VARCHAR(100) NOT NULL,
    `estado` VARCHAR(50) NOT NULL DEFAULT 'en formacion',
    `horas_inasistidas` INTEGER NOT NULL DEFAULT 0,
    `fechaIngreso` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `programaId` INTEGER NOT NULL,

    PRIMARY KEY (`idAPRENDIZ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREDICCION_DESERCION` (
    `idPREDICCION` INTEGER NOT NULL AUTO_INCREMENT,
    `fecha` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `riesgo` VARCHAR(50) NOT NULL,
    `probabilidad` DOUBLE NULL,
    `aprendizId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREDICCION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREDICCION_DEMANDA` (
    `idPREDICCION` INTEGER NOT NULL AUTO_INCREMENT,
    `fecha` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `demanda` DOUBLE NOT NULL,
    `tendencia` VARCHAR(20) NOT NULL,
    `confianza_prediccion` DOUBLE NOT NULL DEFAULT 0,
    `trimestre_objetivo` VARCHAR(20) NOT NULL,
    `accion_sugerida` VARCHAR(20) NOT NULL,
    `programaId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREDICCION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AMBIENTE` ADD CONSTRAINT `AMBIENTE_centroId_fkey` FOREIGN KEY (`centroId`) REFERENCES `CENTRO`(`idCENTRO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_centroId_fkey` FOREIGN KEY (`centroId`) REFERENCES `CENTRO`(`idCENTRO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_programaId_fkey` FOREIGN KEY (`programaId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECOMENDACION` ADD CONSTRAINT `RECOMENDACION_programaElegidoId_fkey` FOREIGN KEY (`programaElegidoId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECOMENDACION` ADD CONSTRAINT `RECOMENDACION_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_aspiranteId_fkey` FOREIGN KEY (`aspiranteId`) REFERENCES `ASPIRANTE`(`idASPIRANTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREGUNTAS` ADD CONSTRAINT `PREGUNTAS_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_aspiranteId_fkey` FOREIGN KEY (`aspiranteId`) REFERENCES `ASPIRANTE`(`idASPIRANTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_preguntaId_fkey` FOREIGN KEY (`preguntaId`) REFERENCES `PREGUNTAS`(`idPREGUNTAS`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `APRENDIZ` ADD CONSTRAINT `APRENDIZ_programaId_fkey` FOREIGN KEY (`programaId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREDICCION_DESERCION` ADD CONSTRAINT `PREDICCION_DESERCION_aprendizId_fkey` FOREIGN KEY (`aprendizId`) REFERENCES `APRENDIZ`(`idAPRENDIZ`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREDICCION_DEMANDA` ADD CONSTRAINT `PREDICCION_DEMANDA_programaId_fkey` FOREIGN KEY (`programaId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE RESTRICT ON UPDATE CASCADE;
